name: "Unit Tests "
description: "Run Unit Tests with Maven"

runs:
  using: "composite"
  steps:
  - name: Run Integration Tests 
    shell: bash
    run: mvn -B test '-Dtest=!org.eclipse.leshan.integration.tests.**' -DfailIfNoTests=false -Dskip.yarn

  - name: Add comment
    if: failure()
    uses: marocchino/sticky-pull-request-comment@v2
    with:
      header: Unit Tests Failed
      message: |
        :x: **Unit Tests failed !** [(more details)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

        Ensure your code build locally using: 
        ```
        mvn clean install
        ```
        Or just launch tests : 
        ```
        mvn test -Dskip.yarn
        ```
        To launch unit tests only : 
        ```
        mvn test '-Dtest=!org.eclipse.leshan.integration.tests.**' -DfailIfNoTests=false -Dskip.yarn
        ```

  - name: Delete comment
    if: success()
    uses: marocchino/sticky-pull-request-comment@v2
    with:
      header: Unit Tests Failed
      delete: true