name: "Add Comment"
description: "Download comment content file, substitute some value, then add the comment on a PR"

inputs:
  pullrequest_id:  
    description: 'Id of the pull request to which we want to add comment'
    required: true
  action_name:  
    description: 'The name of the "action" for which we want to create a comment'
    required: true
  job_url:  
    description: 'url of the concerned job'
    required: true


runs:
  using: "composite"
  steps:

  - name: Download Comment Template
    # unstrusted action use commit ID instead of version 
    uses: Bhacaz/checkout-files@e3e34e7daef91a5f237485bb88a260aee4be29dd #v2
    with:
      files: .github/actions/${{inputs.action_name}}/comment.txt

  - name: Substitute Value in Template
    # unstrusted action use commit ID instead of version 
    uses: bluwy/substitute-string-action@e960a2ca5cfbb2174acafb8be90b7c16218f8dae #v2.0.1
    id: sub
    with:
      _input-file: .github/actions/${{inputs.action_name}}/comment.txt
      _format-key: '###_key_###'
      URL: ${{inputs.job_url}}
      
  - name: Add comment
    # unstrusted action use commit ID instead of version 
    uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 #v2.9.0
    with:
      number: ${{inputs.pullrequest_id}}
      header: ${{inputs.action_name}}
      message: ${{steps.sub.outputs.result}}