name: "Check Java Import"
description: "Check Java Import are well sorted with Maven"

inputs:
  build_status_filename:  
    description: 'Path to build status properties file'
    required: true

runs:
  using: "composite"
  steps:

  - name: display maven version
    id: ver
    shell: bash
    run: mvn -version

  - name: Check Java Import
    id: main
    shell: bash
    run: mvn -B impsort:check

    # Store Step status in Build Status Properties file
  - name: Store Step Status
    if: always()
    # unstrusted action use commit ID instead of version 
    uses: GuillaumeFalourd/write-java-properties-file@c6762204aa02d62718ed285bca4cbcc400c65a10 #v1
    with:
      file_path: ${{inputs.build_status_filename}}
      property: ${{github.action}}
      value: ${{steps.main.outcome}}
