name: "Check code Format"
description: "Check code is well formatted with Maven"

runs:
  using: "composite"
  steps:

  - name: Check Code Format
    id: formatter
    shell: bash
    run: mvn -B formatter:validate

  - name: Add comment
    if: failure()
    uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
    with:
      header: Code Formatter Validation Failed
      message: |
        :x: **Code is not well-formatted !** [(more details)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

        Ensure your code build locally using: 
        ```
        mvn clean install
        ```
        Or just validate code format with : 
        ```
        mvn formatter:validate
        ```
        You can format the code with : 
        ```
        mvn formatter:format
        ```
        See also [How configure your IDE](https://github.com/eclipse/leshan/wiki/Code-&-design-guidelines#configure-your-ide).

  - name: Delete comment
    if: success()
    uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
    with:
      header: Code Formatter Validation Failed
      delete: true