name: "Check Test"
description: "Check pom.xml file are well formatted with Maven"

runs:
  using: "composite"
  steps:

  - name: Check POM formatting
    id: sort_pom
    shell: bash
    run: mvn -B com.github.ekryd.sortpom:sortpom-maven-plugin:verify -PallPom 

  - name: Save PR number
    run: |
      mkdir -p ./failures
      echo "a comment text" > ./failures/sort_pom